// PetGenerator — deterministic procedural pet generation.
//
// Generation is split into two stages:
//   * `draw(seed:)` performs the frozen 31-draw sequence and returns the RAW
//     configuration (colors generated BY ROLE, no repair applied). It is
//     internal so tests can measure how often the validator has to intervene.
//   * `generate(seed:version:)` checks the version then returns
//     `PetConfigurationValidator.validate(draw(seed:))`.
//
// Generator version 1 output is therefore defined as "frozen draw order +
// validation": numeric traits are clamped into their declared ranges and any
// residual low-contrast colors are repaired. Because colors are now drawn per
// role, contrast is satisfied by construction and the validator is only a rare
// safety net. Generator output is always a validator fixed point (idempotent).
//
// FROZEN RANDOM CONSUMPTION ORDER — generator version 1
// ======================================================
// A single `SplitMix64` stream is drawn from `seed`. The values below are
// consumed in EXACTLY this order. This order is FROZEN FOREVER for generator
// version 1: any change (reordering, inserting, or removing a draw) alters the
// output for every existing seed and MUST instead be introduced under a new
// generator version. Categorical picks use uniform weighting over the trait's
// `allCases` (the declared v1 weighting). Each color slot still consumes
// exactly three draws (a, b, c) in order, but they are interpreted PER ROLE so
// each color lands in a band appropriate to its use. `baseHue` is the hue drawn
// for `baseColor` (slot 8); hue-relative roles offset from it. Hue offsets are
// wrapped into [0, 1) by pure arithmetic (`RGBAColor.hsb` also wraps).
//
//  1. body.bodyShape            (element)
//  2. body.bodyScale            value(in: 0.90...1.10)
//  3. body.headScale            value(in: 0.90...1.15)
//  4. body.furStyle             (element)
//  5. body.patternStyle         (element)
//  6. body.patternDensity       value(in: 0...1)
//  7. body.patternScale         value(in: 0.75...1.25)
//  8. palette.baseColor         coat color
//                               hue = a.unitDouble()  (== baseHue)
//                               sat = value(in: 0.22...0.52)
//                               bri = value(in: 0.72...0.90)
//                               NOTE: the brightness ceiling is 0.90 (not 0.96).
//                               A pure-white color is only ~0.13 RGB-distant from
//                               a near-white base, so with a 0.96 ceiling no
//                               *lighter* secondary can ever be the validator's
//                               required 0.28 away from a pale base — making
//                               "secondary lighter than base" and "secondary
//                               >=0.28 from base" mutually exclusive for pale
//                               bases. Capping base brightness keeps the coat off
//                               near-white so a light cream secondary satisfies
//                               both by construction. See report deviation note.
//  9. palette.secondaryColor    soft cream/light version of the coat (chest & muzzle)
//                               hue = baseHue + value(in: -0.04...0.04) wrapped
//                               sat = value(in: 0.02...0.06)
//                               bri = value(in: 0.99...1.0)
//                               (near-white so it stays >=0.28 from even a pale
//                                base by construction; see PetGenerator note)
// 10. palette.accentColor       complementary tint for tufts/tips
//                               hue = baseHue + value(in: 0.30...0.70) wrapped
//                               sat = value(in: 0.35...0.60)
//                               bri = value(in: 0.80...0.95)
// 11. face.eyeShape             (element)
// 12. face.eyeScale             value(in: 0.85...1.15)
// 13. face.irisColor            deep glossy eye (near-black with colored rim)
//                               hue = a.unitDouble()
//                               sat = value(in: 0.30...0.70)
//                               bri = value(in: 0.14...0.34)
// 14. face.pupilStyle           (element)
// 15. face.muzzleStyle          (element)
// 16. face.noseStyle            (element)
// 17. face.noseColor            rose
//                               hue = value(in: 0.93...1.0) wrapped
//                               sat = value(in: 0.30...0.50)
//                               bri = value(in: 0.58...0.76)
// 18. face.cheekStyle           (element)
// 19. face.cheekColor           soft blush
//                               hue = value(in: 0.94...1.0) wrapped
//                               sat = value(in: 0.18...0.32)
//                               bri = value(in: 0.92...1.0)
// 20. ears.earStyle             (element)
// 21. ears.earScale             value(in: 0.80...1.20)
// 22. ears.earAngle             value(in: 0...1)
// 23. tail.tailStyle            (element)
// 24. tail.tailLength           value(in: 0.80...1.20)
// 25. tail.tailThickness        value(in: 0.80...1.20)
// 26. details.headTuftStyle     (element)
// 27. details.chestTuftStyle    (element)
// 28. details.magicalFeature    (element)
// 29. details.magicalColor      luminous pastel
//                               hue = a.unitDouble()
//                               sat = value(in: 0.25...0.50)
//                               bri = value(in: 0.90...1.0)
// 30. details.magicalIntensity  value(in: 0...1)
// 31. motionPersonality         (element)

public enum PetGeneratorError: Error, Equatable {
    case unsupportedVersion(Int)
}

public enum PetGenerator {
    public static let currentVersion = 1

    public static func generate(seed: UInt64, version: Int) throws -> PetConfiguration {
        guard version == 1 else {
            throw PetGeneratorError.unsupportedVersion(version)
        }
        return try PetConfigurationValidator.validate(draw(seed: seed))
    }

    /// Performs the frozen 31-draw sequence and returns the RAW configuration
    /// (colors generated by role, no repair). Internal so tests can measure how
    /// rarely the validator needs to intervene.
    static func draw(seed: UInt64) -> PetConfiguration {
        var random = SplitMix64(seed: seed)

        // Draw every value into a local `let` in the frozen order BEFORE
        // constructing any struct, so struct argument evaluation order can
        // never influence the random consumption order.

        // Body
        let bodyShape = random.element(from: Array(BodyShape.allCases))
        let bodyScale = random.value(in: 0.90...1.10)
        let headScale = random.value(in: 0.90...1.15)
        let furStyle = random.element(from: Array(FurStyle.allCases))
        let patternStyle = random.element(from: Array(PatternStyle.allCases))
        let patternDensity = random.value(in: 0...1)
        let patternScale = random.value(in: 0.75...1.25)

        // Palette — baseColor first so its hue can anchor the hue-relative roles.
        let (baseColor, baseHue) = self.baseColor(using: &random)
        let secondaryColor = self.secondaryColor(baseHue: baseHue, using: &random)
        let accentColor = self.accentColor(baseHue: baseHue, using: &random)

        // Face
        let eyeShape = random.element(from: Array(EyeShape.allCases))
        let eyeScale = random.value(in: 0.85...1.15)
        let irisColor = self.irisColor(using: &random)
        let pupilStyle = random.element(from: Array(PupilStyle.allCases))
        let muzzleStyle = random.element(from: Array(MuzzleStyle.allCases))
        let noseStyle = random.element(from: Array(NoseStyle.allCases))
        let noseColor = self.noseColor(using: &random)
        let cheekStyle = random.element(from: Array(CheekStyle.allCases))
        let cheekColor = self.cheekColor(using: &random)

        // Ears
        let earStyle = random.element(from: Array(EarStyle.allCases))
        let earScale = random.value(in: 0.80...1.20)
        let earAngle = random.value(in: 0...1)

        // Tail
        let tailStyle = random.element(from: Array(TailStyle.allCases))
        let tailLength = random.value(in: 0.80...1.20)
        let tailThickness = random.value(in: 0.80...1.20)

        // Details
        let headTuftStyle = random.element(from: Array(HeadTuftStyle.allCases))
        let chestTuftStyle = random.element(from: Array(ChestTuftStyle.allCases))
        let magicalFeature = random.element(from: Array(MagicalFeature.allCases))
        let magicalColor = self.magicalColor(using: &random)
        let magicalIntensity = random.value(in: 0...1)

        // Personality
        let motionPersonality = random.element(from: Array(MotionPersonality.allCases))

        return PetConfiguration(
            formatVersion: 1,
            generatorVersion: 1,
            seed: seed,
            body: BodyTraits(
                bodyShape: bodyShape,
                bodyScale: bodyScale,
                headScale: headScale,
                furStyle: furStyle,
                patternStyle: patternStyle,
                patternDensity: patternDensity,
                patternScale: patternScale
            ),
            palette: Palette(
                baseColor: baseColor,
                secondaryColor: secondaryColor,
                accentColor: accentColor
            ),
            face: FaceTraits(
                eyeShape: eyeShape,
                eyeScale: eyeScale,
                irisColor: irisColor,
                pupilStyle: pupilStyle,
                muzzleStyle: muzzleStyle,
                noseStyle: noseStyle,
                noseColor: noseColor,
                cheekStyle: cheekStyle,
                cheekColor: cheekColor
            ),
            ears: EarTraits(
                earStyle: earStyle,
                earScale: earScale,
                earAngle: earAngle
            ),
            tail: TailTraits(
                tailStyle: tailStyle,
                tailLength: tailLength,
                tailThickness: tailThickness
            ),
            details: DetailTraits(
                headTuftStyle: headTuftStyle,
                chestTuftStyle: chestTuftStyle,
                magicalFeature: magicalFeature,
                magicalColor: magicalColor,
                magicalIntensity: magicalIntensity
            ),
            motionPersonality: motionPersonality
        )
    }

    // MARK: - Role-based color helpers
    //
    // Each helper consumes exactly three draws (a, b, c) in order and maps them
    // to hue/saturation/brightness bands chosen for that color's role. Hue is
    // wrapped into [0, 1) by pure arithmetic; `RGBAColor.hsb` also wraps, so an
    // unwrapped hue would be safe too, but wrapping here keeps `hue` sensible
    // for the hue-relative roles.

    /// Wraps `hue` into [0, 1) using only arithmetic (no libm transcendentals).
    private static func wrapHue(_ hue: Double) -> Double {
        var wrapped = hue.truncatingRemainder(dividingBy: 1)
        if wrapped < 0 { wrapped += 1 }
        return wrapped
    }

    /// Builds a color from three explicit component values.
    private static func makeColor(hue: Double, saturation: Double, brightness: Double) -> RGBAColor {
        RGBAColor.hsb(hue: wrapHue(hue), saturation: saturation, brightness: brightness)
    }

    /// slot 8 — coat color (unchanged bands). Returns the color together with
    /// the raw drawn hue (`baseHue`) so hue-relative roles can offset from it.
    private static func baseColor(using random: inout SplitMix64) -> (RGBAColor, Double) {
        let hue = random.unitDouble()
        let saturation = random.value(in: 0.22...0.52)
        let brightness = random.value(in: 0.72...0.90)
        return (makeColor(hue: hue, saturation: saturation, brightness: brightness), hue)
    }

    /// slot 9 — soft cream/light version of the coat for chest & muzzle.
    /// The band is pushed toward near-white (very low saturation, brightness
    /// ~1.0) so the cream stays at least the validator's 0.28 RGB distance from
    /// the base by construction and is always lighter than it. A light color
    /// cannot be both lighter than a near-white base AND 0.28 away from it, so
    /// the base brightness ceiling (slot 8) is capped at 0.90 to keep the coat
    /// off near-white. Together these make secondary repair never fire over
    /// seeds 0..<1000. See report deviation note.
    private static func secondaryColor(baseHue: Double, using random: inout SplitMix64) -> RGBAColor {
        let hue = baseHue + random.value(in: -0.04...0.04)
        let saturation = random.value(in: 0.02...0.06)
        let brightness = random.value(in: 0.99...1.0)
        return makeColor(hue: hue, saturation: saturation, brightness: brightness)
    }

    /// slot 10 — complementary tint for tufts/tips.
    private static func accentColor(baseHue: Double, using random: inout SplitMix64) -> RGBAColor {
        let hue = baseHue + random.value(in: 0.30...0.70)
        let saturation = random.value(in: 0.35...0.60)
        let brightness = random.value(in: 0.80...0.95)
        return makeColor(hue: hue, saturation: saturation, brightness: brightness)
    }

    /// slot 13 — deep glossy eye (near-black with a colored rim).
    private static func irisColor(using random: inout SplitMix64) -> RGBAColor {
        let hue = random.unitDouble()
        let saturation = random.value(in: 0.30...0.70)
        let brightness = random.value(in: 0.14...0.34)
        return makeColor(hue: hue, saturation: saturation, brightness: brightness)
    }

    /// slot 17 — rose.
    private static func noseColor(using random: inout SplitMix64) -> RGBAColor {
        let hue = random.value(in: 0.93...1.0)
        let saturation = random.value(in: 0.30...0.50)
        let brightness = random.value(in: 0.58...0.76)
        return makeColor(hue: hue, saturation: saturation, brightness: brightness)
    }

    /// slot 19 — soft blush.
    private static func cheekColor(using random: inout SplitMix64) -> RGBAColor {
        let hue = random.value(in: 0.94...1.0)
        let saturation = random.value(in: 0.18...0.32)
        let brightness = random.value(in: 0.92...1.0)
        return makeColor(hue: hue, saturation: saturation, brightness: brightness)
    }

    /// slot 29 — luminous pastel.
    private static func magicalColor(using random: inout SplitMix64) -> RGBAColor {
        let hue = random.unitDouble()
        let saturation = random.value(in: 0.25...0.50)
        let brightness = random.value(in: 0.90...1.0)
        return makeColor(hue: hue, saturation: saturation, brightness: brightness)
    }
}
